## Deprecated Netlify configuration retained only for history. Redirects now handled by Cloudflare Pages `_redirects` file.
[[redirects]]
from = "/en/latest*"
to = "/"
status = 301
force = false

[[redirects]]
from = "/cp-api"
to = "https://api-docs.connexcs.com/"
status = 301
force = true

[[plugins]]
package = "@netlify/plugin-sitemap"


